### ISSUE TITLE
attempt to set an attribute on NULL error when running scdesign3()

### ISSUE THREAD

**Issue by XiaPoppy** [SONGDONGYUAN1994/scDesign3#11]
Hi, 

I am just starting working with scDesign3 package and following the [tutorial about CITE-seq data](https://songdongyuan1994.github.io/scDesign3/docs/articles/scDesign3-CITEseq-vignette.html). Two weeks ago everything worked, but now I get this error message "Error in names(answer) <- dots[[1L]] :
attempt to set an attribute on NULL"  after
`example_simu <- scdesign3(
    sce = example_sce,
    assay_use = "counts",
    celltype = "cell_type",
    pseudotime = NULL,
    spatial = NULL,
    other_covariates = NULL,
    mu_formula = "cell_type",
    sigma_formula = "cell_type",
    family_use = "nb",
    n_cores = 2,
    usebam = FALSE,
    corr_formula = "cell_type",
    copula = "vine",
    DT = TRUE,
    pseudo_obs = FALSE,
    return_model = FALSE,
    nonzerovar = TRUE,
    nonnegative = TRUE
  )`

it is so weird, maybe do you have any idea for that? Thanks!

**Comment by SONGDONGYUAN1994** [comment]
Hi,
Sorry for the bug we introduced in the previous update! Now we fixed it and please reinstall `scDesign3`.

By the way, if you want to use more features, please use the `gaussian` copula instead of `vine` copula since it is not very scalable. 

Best,
Dongyuan

**Comment by XiaPoppy** [comment]
Hi, 
Thanks for your quick reply. I removed and installed scDesign3 version from GitHub
`devtools::install_github("SONGDONGYUAN1994/scDesign3")`
 but it seems that the problem is not solved. 

for sure i will copy the codes I ran in below. 
`library(scDesign3)
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(scales)
library(ggh4x)

example_sce <- readRDS(url("https://figshare.com/ndownloader/files/40581968"))
print(example_sce)
#To save computational time, we only use the top 100 genes and six more genes with protein and RNA abundance information.
keep_gene <- c("CD4",  "CD14", "CD19", "CD34", "CD3E", "CD8A")
keep_adt <- c("ADT_CD4", "ADT_CD14", "ADT_CD19", "ADT_CD34", "ADT_CD3", "ADT_CD8")
keep <- c(keep_gene, keep_adt)
idx <- which(rownames(example_sce) %in% keep)
idx <- c(1:100,idx)
example_sce <- example_sce[idx,]
logcounts(example_sce) <- log1p(counts(example_sce))

set.seed(123)
example_simu <- scdesign3(
    sce = example_sce,
    assay_use = "counts",
    celltype = "cell_type",
    pseudotime = NULL,
    spatial = NULL,
    other_covariates = NULL,
    mu_formula = "cell_type",
    sigma_formula = "cell_type",
    family_use = "nb",
    n_cores = 2,
    usebam = FALSE,
    corr_formula = "cell_type",
    copula = "gaussian",
    DT = TRUE,
    pseudo_obs = FALSE,
    return_model = FALSE,
    nonzerovar = TRUE,
    nonnegative = TRUE
  )
`

**Comment by SONGDONGYUAN1994** [comment]
Hi Danyang,
Could you please post the error message? Thanks!

Best regards,
Dongyuan

**Comment by XiaPoppy** [comment]
Hi Dongyuan,

 the whole error message is as follows: 
`Error in names(answer) <- dots[[1L]] :
attempt to set an attribute on NULL`

`5. paraFunc(fit_ model_func, gene = feature_names, family-gene = family_use,mc.cores = n_cores, MoreArgs = list(dat_use = dat_cov, mu_formula = mu formula.sigma_formula = sigma_formula,predictor = predictor,count_mat = count mat)，SIMPLIFY = FALSE)`

`4. withCallingHandlers(expr, message = function(c) if (inherits(c,classes)) tryInvokeRestart("muffleMessage"))
`
`3. suppressMessages(paraFunc(fit_model_func,gene = feature_names,family-gene = family_use, mc.cores = n_cores, MoreArgs = list(dat_use = dat_cov.mu_formula = mu_formula,sigma_formula = sigma_formula,predictor = predictor, count_mat = count_mat)，SIMPLIFY = FALSE))`

`2. fit_ marginal(mu_formula = mu_formula, sigma _formula = sigma_ formula,n_cores = n_cores, data = input data, family use = family use,usebam = usebam,parallelization = parallelization，BPPARAM = BPPARAM.trace = trace)`

`1. scdesign3(sce = example_sce, assay_use = "counts", celltype = "cell_type"pseudotime = NULL，spatial = NULL，other_covariates = NULL，mu_formula = "cell_type", sigma_formula = "cell_type", family_use = "nb"n_cores = 2, usebam = FALSE, corr_formula ="cell_type", ..`.

Best,
Danyang

**Comment by SONGDONGYUAN1994** [comment]
Hi Danyang,
This is weird since this is the first time I have met this error. Some questions:
1. What is your OS? Can you try `n_cores = 1`?
2. scDesign3 prints out its progress. Could you show us the progress message so that we can know which step you stopped?

Best,
Dongyuan

**Comment by XiaPoppy** [comment]
Hi Dongyuan,

1. Mac m1, try n_cores=1 and run codes again -> oh **it does work!**  Thanks!

2. process message appeared last time(when error exists): 
```
Input Data Construction Start
Input Data Construction End
Start Marginal Fitting
Warning: scheduled cores 1, 2 did not deliver results, all values of the jobs will be affectedError in 
names(answer) <- dots[[1L]] : 
   attempt to set an attribute on NULL
```
Thanks a lot! 

Best,
Danyang Xia

**Comment by SONGDONGYUAN1994** [comment]
Hi Danyang,
Sounds great! It seems like there was a parallelization issue for your OS. Let me know if you have further issues.

Best,
Dongyuan
